version: "3.9"

services:

  traefik:
    image: traefik:v3
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  postgres:
    image: postgres:15
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - ../.env
    ports:
      - "9001:9001"
    volumes:
      - minio-data:/data

  grafana:
    image: grafana/grafana
    env_file:
      - ../.env
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  postgres-data:
  portainer-data:
  minio-data:
